import './globals.css';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app'

const inter = Inter({
  subsets: ['latin']
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
      </body>
    </html>
  )
}
